// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5
// Source: user.proto

package server

import (
	"context"

	"rpc/internal/logic/usercreate"
	"rpc/internal/svc"
	"rpc/types/user"
)

type UserCreateServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserCreateServer
}

func NewUserCreateServer(svcCtx *svc.ServiceContext) *UserCreateServer {
	return &UserCreateServer{
		svcCtx: svcCtx,
	}
}

func (s *UserCreateServer) UserCreate(ctx context.Context, in *user.UserCreateRequest) (*user.UserCreateResponse, error) {
	l := usercreatelogic.NewUserCreateLogic(ctx, s.svcCtx)
	return l.UserCreate(in)
}
