# Typo check: https://github.com/crate-ci/typos

[files]
extend-exclude = [
    "go.mod",
    "go.sum",
    "hack/*",
    "check_branch_name.sh",
    "*/licenses/*",
    "bootstrap.*.js",
    "go.work.sum"
]

[default.extend-identifiers]
